<?php

namespace Tests\Feature\Livewire\Ipc\Concerns;

use App\Domains\Permission\Models\Permission;
use App\Domains\Role\Models\Role;
use App\Domains\User\Models\User;
use App\Shared\Services\CacheService;

trait BuildsIpcUsers
{
    protected function createUserWithPermissions(array $permissions): User
    {
        $user = User::factory()->create();

        $role = Role::query()->create([
            'name' => 'role-'.uniqid(),
            'display_name' => 'Test Role',
            'description' => 'Role for IPC Livewire tests',
            'is_active' => true,
        ]);

        $permissionIds = collect($permissions)
            ->map(fn (string $permission) => Permission::query()->firstOrCreate(
                ['name' => $permission],
                [
                    'display_name' => strtoupper(str_replace(['.', '_'], ' ', $permission)),
                    'description' => 'Generated by IPC Livewire tests',
                    'group' => explode('.', $permission)[0],
                    'is_active' => true,
                ]
            )->id)
            ->all();

        $role->permissions()->sync($permissionIds);
        CacheService::clearRoleCache($role->id);

        $user->assignRole($role);
        $user->refresh();

        return $user;
    }
}
