<?php

namespace Tests\Feature\Livewire\Document\Concerns;

use App\Domains\Permission\Models\Permission;
use App\Domains\Role\Models\Role;
use App\Domains\User\Models\User;
use App\Shared\Services\CacheService;

trait BuildsDocumentFixtures
{
    protected function createUserWithAccess(array $permissions = [], array $roles = []): User
    {
        $user = User::factory()->create();

        foreach ($roles as $roleName) {
            $role = Role::query()->firstOrCreate(
                ['name' => $roleName],
                [
                    'display_name' => ucwords(str_replace('-', ' ', $roleName)),
                    'description' => 'Generated by document tests',
                    'is_active' => true,
                ]
            );

            $user->roles()->syncWithoutDetaching([$role->id]);
            CacheService::clearRoleCache($role->id);
        }

        if ($permissions !== []) {
            $role = Role::query()->create([
                'name' => 'document-test-role-'.uniqid(),
                'display_name' => 'Document Test Role',
                'description' => 'Generated by document tests',
                'is_active' => true,
            ]);

            $permissionIds = collect($permissions)
                ->map(fn (string $permission) => Permission::query()->firstOrCreate(
                    ['name' => $permission],
                    [
                        'display_name' => strtoupper(str_replace(['.', '_'], ' ', $permission)),
                        'description' => 'Generated by document tests',
                        'group' => explode('.', $permission)[0],
                        'is_active' => true,
                    ]
                )->id)
                ->all();

            $role->permissions()->sync($permissionIds);
            $user->roles()->syncWithoutDetaching([$role->id]);
            CacheService::clearRoleCache($role->id);
        }

        CacheService::clearUserCache($user->id);

        return $user->refresh();
    }
}
